apiVersion: v1
kind: Service
metadata:
  name: api-order
  labels:
    app: api-order
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  selector:
    app: api-order