apiVersion: v1
kind: Service
metadata:
  name: api-mock
  labels:
    app: api-mock
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8084
      protocol: TCP
  selector:
    app: api-mock