apiVersion: v1
kind: Secret
metadata:
  name: dev-secret
type: Opaque
data:
  mock-db-url: amRiYzpteXNxbDovL3lrZS1kZXYubXlzcWwuZGF0YWJhc2UuYXp1cmUuY29tOjMzMDYveW9rYWlfZXh0ZXJuYWw/Y3JlYXRlRGF0YWJhc2VJZk5vdEV4aXN0PXRydWU=
  db-url: amRiYzpteXNxbDovL3lrZS1kZXYubXlzcWwuZGF0YWJhc2UuYXp1cmUuY29tOjMzMDYveW9rYWk/Y3JlYXRlRGF0YWJhc2VJZk5vdEV4aXN0PXRydWU=
  db-username: eWtlQHlrZS1kZXY=
  db-password: RGV2WW9rYWlFeHByZXNzQDIwMjIh
  db-driver: Y29tLm15c3FsLmNqLmpkYmMuRHJpdmVy
  allowed-origins: aHR0cDovL2xvY2FsaG9zdDozMDAw
  api-internal: aHR0cDovL2xvY2FsaG9zdDo4MDAw
  api-auth: aHR0cDovL2xvY2FsaG9zdDo4MDgw
  api-order: aHR0cDovL2xvY2FsaG9zdDo4MDgx
  api-payment: aHR0cDovL2xvY2FsaG9zdDo4MDgy
  api-inventory: aHR0cDovL2xvY2FsaG9zdDo4MDgz
  api-mock: aHR0cDovL2xvY2FsaG9zdDo4MDg0
  yokai-admin-username: YWRtaW5AeW9rYWlleHByZXNzLmNvbQ==
  yokai-admin-password: cGFzc3dvcmQ=
  mail-server-host: c210cC5nbWFpbC5jb20=
  mail-server-port: NTg3
  mail-server-protocol: c210cA==
  mail-server-username: Y29jb29uLjE3MThAZ21haWwuY29t
  mail-server-password: Q29uYW4wOTA4Lg==
  mail-server-from: Y29jb29uLjE3MThAZ21haWwuY29t
  bt-env: c2FuZGJveA==
  bt-merchant-id: dDdzdjhwcjkzaDY2YmpuYw==
  bt-public-key: dzdzYnJrcGRkaDRnOGg5OA==
  bt-private-key: Nzg3Y2U4ODY4ZjIyOWIzOGYxNjhlMWM4ZDE1N2U0NTc=